FROM tensorflow/tensorflow:2.1.0-py3

# OpenCV dependencies
RUN apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6

RUN pip install --no-cache-dir \
    fastestimator==1.0.6