FROM tensorflow/tensorflow:2.0.0rc0-py3-jupyter

# OpenCV dependencies
RUN apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6

RUN pip install --no-cache-dir \
    opencv-python \
    fastestimator==1.0a0